config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'
  # get "/profile/:username" => "users#profile", as: :profile

  devise_for :users, :path => 'account'

  get 'users/:username/profile', to: 'users#show', as: :user
  resources :users, param: :username do
    get 'users/:username/recipes', to: 'users#recipes', as: :recipes
    member do
      get :following, :followers
    end
  end
  
  resources :recipes do
    resources :comments, module: :recipes
  end
  
  resources :comments do
    resources :comments, module: :comments
  end

  resources :relationships, only: [:create, :destroy]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActionView::RecordIdentifier
  
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: "Comment"
  has_many :comments, foreign_key: :parent_id, dependent: :destroy
  
  validates :body, presence: true

  def set_nesting
    if self.parent.present? && self.parent.nesting.present?
      self.nesting = self.parent.nesting + 1
    else
      self.nesting = 1
    end
  end

  def self.max_nesting
    2
  end

  after_create_commit do
    broadcast_append_to [commentable, :comments], target: "#{dom_id(parent || commentable)}_comments", partial: "comments/comment_with_replies"
  end

  after_update_commit do
    broadcast_replace_to self
  end

  after_destroy_commit do
    broadcast_remove_to self
    broadcast_action_to self, action: :remove, target: "#{dom_id(self)}_with_comments"
  end
end

app/controllers/comments/comments_controller.rb
class Comments::CommentsController < ApplicationController
  include Commentable

  before_action :set_commentable

  private

    def set_commentable
      @parent = Comment.find(params[:comment_id])
      @commentable = @parent.commentable
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment

  def show
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.turbo_stream {}
      format.html { redirect_to @comment.commentable }
    end
  end

  private

  def set_comment
    @comment = current_user.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/recipes/comments_controller.rb
class Recipes::CommentsController < ApplicationController
  include Commentable

  before_action :set_commentable

  private

    def set_commentable
      @commentable = Recipe.find(params[:recipe_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def reply_to_comment_id(comment, nesting)
    nesting = 1 unless nesting.present?
    max_nesting = Comment.max_nesting
    if max_nesting.blank? || nesting < max_nesting
      comment.id
    else
      comment.parent_id
    end
  end
end

app/views/comments/_comment.html.erb
<%= turbo_stream_from comment %>

<%= turbo_frame_tag comment, target: "_top" do %>
  <div class="d-flex justify-content-between">
    <div>
    <% if comment.parent.nil? %>
      <strong><%= link_to comment.user.first_name, user_path(comment.user.id) %></strong>
    <% else %>
      <strong><%= link_to comment.user.first_name, user_path(comment.user.id) %></strong> replied to <strong><%= link_to comment.parent&.user&.first_name, user_path(comment.parent&.user&.id) %></strong>:
    <% end %>
    </div>
    <div class="protected-links d-none" data-user-id="<%= comment.user_id %>">
      <%= link_to "Edit", edit_comment_path(comment), class: "mr-2" %>
      <%= button_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  </div>
  <%= comment.body %>
<% end %>

app/views/comments/_comment_with_replies.html.erb
<%= turbo_stream_from comment, :comments %>

<div id="<%= dom_id(comment) %>_with_comments" data-controller="comment">
  <%= render comment %>

  <div class="text-sm">
    <%= link_to "Reply", "#", data: { action: "click->comment#toggle" } %>
  </div>

<% if comment.nesting.blank? || comment.nesting < Comment.max_nesting %>
  <div class="pl-3 border-left" id="<%= dom_id(comment) %>_comments">
    <%= render partial: "comments/form", locals: { commentable: comment, comment: Comment.new, data: { comment_target: "form" }, class: "d-none" } %>
    <div class="d-none" data-comment-target="unhide">    
      <%= render partial: "comments/comment_with_replies", collection: comment.comments, as: :comment %>
    </div>
  </div>  
<% else %>
  <div id="<%= dom_id(comment) %>_comments">
    <%= render partial: "comments/form", locals: { commentable: comment, comment: Comment.new, data: { comment_target: "form" }, class: "d-none" } %>
    <div class="d-none" data-comment-target="unhide">    
      <%= render partial: "comments/comment_with_replies", collection: comment.comments, as: :comment %>
    </div>
  </div>  
<% end %>
<% if comment.comments.present? %>
  <div>
    <%= link_to "Show More", "#", data: { action: "click->comment#show", comment_target: "hide" } %>
  </div> 
<% end %>
</div>

app/views/comments/_form.html.erb
<% model = [local_assigns[:commentable], comment].compact %>

<%= form_with model: [commentable, comment],
  id: dom_id_for_records(*model),
  data: local_assigns[:data],
  class: ["my-4"] + Array.wrap(local_assigns[:class]) do |form| %>

  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <%= form.text_area :body, id: "#{dom_id_for_records(*model)}_body" %>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to "Cancel", comment, class: "btn btn-link" if form.object.persisted? %>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render "form", comment: @comment %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render @comment %>
<% end %>