config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'
  # get "/profile/:username" => "users#profile", as: :profile

  devise_for :users, :path => 'account'

  get 'users/:username/profile', to: 'users#show', as: :user
  resources :users, param: :username do
    get 'users/:username/recipes', to: 'users#recipes', as: :recipes
    member do
      get :following, :followers
    end
  end
  
  resources :recipes do
    resources :comments, module: :recipes
  end
  
  resources :comments do
    resources :comments, module: :comments
  end

  resources :relationships, only: [:create, :destroy]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, inverse_of: :recipe, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_many :directions
  has_many :comments, as: :commentable
  has_one_attached :image

  accepts_nested_attributes_for :recipe_ingredients, reject_if: :all_blank, allow_destroy: true

  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

  def self.categories
    ['Breakfast', 'Lunch', 'Dinner', 'Dessert', 'Soup', 'Salad', 'Sauce', 'Appetizer', 'Side Dish']
  end
end

app/controllers/recipes/comments_controller.rb
class Recipes::CommentsController < ApplicationController
  include Commentable

  before_action :set_commentable

  private

    def set_commentable
      @commentable = Recipe.find(params[:recipe_id])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show,:edit,:update,:destroy]
  
  def index
    @recipes = Recipe.all
  end

  def new
    if user_signed_in?
      @recipe = Recipe.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.save
      flash[:success] = "Recipe successfully saved."

      respond_to do |f|
        f.html { redirect_to recipe_path(@recipe) }
        f.json { render json: @recipe }
      end
    else
      render :new
    end
  end

  def show
    respond_to do |f|
      f.html { render :show }
      f.json { render json:  @recipe }
    end
  end

  def edit
    
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
      flash[:success] = "Recipe successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Recipe successfully deleted."
    redirect_to recipes_path
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(
      :name,
      :category,
      :prep_time,
      :cook_time,
      :user_id,
      :image,
      recipe_ingredients_attributes: [
      :id,
      :recipe_id,
      :ingredient_id,
      :quantity,
      :_destroy,
      ingredient_attributes: [:id, :name, :_destroy]],
      directions_attributes: [:id, :body, :_destroy])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def recipe_image recipe
    image = recipe.image.present? ? recipe.image : "https://via.placeholder.com/500x500.png?text=No+image+to+display"
    image_tag(image, class: "img-fluid")
  end

  def recipe_thumbnail recipe
    image = recipe.image.present? ? recipe.image : "https://via.placeholder.com/500x500.png?text=No+image+to+display"
    image_tag(image, class: "recipe-thumbnail img-fluid img-thumbnail")
  end
end

app/views/recipes/_direction_fields.html.erb
<%= content_tag :div, class: "nested-direction-fields", data: { new_record: form.object.new_record? } do %>
  <div class="form-inline">
    <div class="form-group">
      <%= form.text_field(:body, class: "form-control", placeholder: "Step (Ex: Fold in slowly)") %>
      <%= link_to "Remove", "#", data: { action: "click->nested-direction-form#remove_association" } %>
    </div>
  </div>
  <%= form.hidden_field :_destroy, as: :hidden %>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<%= render 'shared/errors', object: f.object %>
<div class="row">
  <div class="col text-center" id="form-title">
    <h1>Add A New Recipe</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h3>Recipe Info</h3>
  </div>
</div>
<div class="row" id="recipe-info">
  <div class="col-md-6">
    <%= f.text_field(:name, class: "form-control", placeholder: "Recipe Name") %>
  </div>
  <div class="col-md-4 ml-auto">
    <%= f.select :category, options_for_select(Recipe.categories), :prompt => "Select a category" %>
  </div>
</div>
<div class="row" id="recipe-image">
  <div class="col">
    <h3>Recipe Image</h3>
    <%= f.file_field :image %>
  </div>
</div>

<div class="row">
  <div class="col">
    <h3>Time</h3>
  </div>
</div>
<div class="row" id="cook-prep-time">
  <div class="col">
    <div class="input-group mb-3 w-50">
      <%= f.text_field(:prep_time, class: "form-control", placeholder: "Prep Time") %>
      <span class="input-group-text" id="basic-addon2">minute(s)</span><br>
    </div>
  </div>
  <div class="col">
    <div class="input-group mb-3 w-50">
      <%= f.text_field(:cook_time, class: "form-control", placeholder: "Cook Time") %>
      <span class="input-group-text" id="basic-addon2">minute(s)</span><br>
    </div>
  </div>
</div>

<div class="row" id="ingredients-directions-fields">
  <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6">
    <h3>Ingredients</h3>
  <div data-controller="nested-ingredient">
    <template data-nested-ingredient-target="template">
      <%= f.fields_for :recipe_ingredients, RecipeIngredient.new, child_index: 'NEW_RECORD' do |recipe_ingredient| %>
        <%= render "recipe_ingredient_fields", form: recipe_ingredient %>
      <% end %>
    </template>

    <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
      <%= render "recipe_ingredient_fields", form: recipe_ingredient %>
    <% end %>

    <div class="mb-3" data-nested-ingredient-target="links">
      <%= link_to "Add Ingredient", "#", class: "btn btn-outline-primary", data: { action: "click->nested-ingredient#add_association" } %>
    </div>
  </div>

  <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6">
    <h3>Directions</h3>
    <div data-controller="nested-direction">
      <template data-nested-direction-target="template">    
        <%= f.fields_for :directions, Direction.new, child_index: 'NEW_RECORD' do |direction| %>
          <%= render "direction_fields", form: direction %>
        <% end %>
      </template>

      <%= f.fields_for(:directions) do |direction| %>
        <%= render "direction_fields", form: direction %>
      <% end %>

      <div class="mb-3" data-nested-direction-target="links">
        <%= link_to "Add Step", "#", class: "btn btn-outline-secondary", data:
        { action: "click->nested-direction#add_association" } %>
      </div>
    </div>
  </div>
</div>
<div class="row" id="submitted">
  <div class="col">
    <div class="actions">
      <%= f.hidden_field(:user_id, value: current_user.id) %>
      <%= f.submit class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>
  <div class="col">
    <%= link_to "Cancel", recipes_path, class: "btn btn-danger" %>
  </div>
</div>

app/views/recipes/_recipe_ingredient_fields.html.erb
<%= content_tag :div, class: "nested-ingredient-fields", data: { new_record: form.object.new_record? } do %>
  <div class="form-inline">
    <div class="form-group">
      <%= form.text_field(:quantity, class: "form-control w-40", placeholder: "Quantity") %>

      <%= form.fields_for :ingredient, Ingredient.new do |ri_ingredient| %>
      <%= ri_ingredient.text_field(:name, class: "form-control w-40", placeholder: "Ingredient Name") %>
      <%= form.hidden_field :ingredient_id, as: :hidden %>
      <% end %>
      <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %>
    </div>
  </div>
  <%= form.hidden_field :_destroy, as: :hidden %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Your Recipe</h1>

<%= render "form", recipe: @recipe, submit_btn: "Update" %>
<%= link_to "Cancel", user_path(@recipe.user), class: "btn btn-danger" %>

app/views/recipes/index.html.erb
<div class="text-center">
  <h1>Recipes</h1>
</div>
<div class="row">
  <% @recipes.each do |recipe| %>
  <div class="col-6 col-md-4">
    <div class="card">
    <%= recipe_thumbnail recipe %>
      <div class="card-body">
        <h5 class="card-title"><%= recipe.name.titleize %></h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <%= link_to "View Recipe", recipe_path(recipe)%>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>Create Your Recipe</h1>

<div class="form-group">
  <div class="panel-body">
    <%= render "form", recipe: @recipe, submit_btn: "Create Recipe" %>
  </div>
</div>

app/views/recipes/show.html.erb
<section class="container" data-controller="protected" data-protected-refresh-interval-value="10">
<div class="row">
<div class="col col-md-8">
<%= recipe_image @recipe %>
<h4 class="recipe-creator"> Recipe by: <%= link_to @recipe.user.first_name.capitalize, user_path(@recipe.user.id), id: "user" %></h4>
<h1 class="recipe-header">
<%= @recipe.name.split.map(&:capitalize).join(' ') %>
</h1>
<div class="recipe-info">
<p>Category: <strong><%= @recipe.category %></strong></p>
<p>Prep: <strong><%= @recipe.prep_time %> min</strong></p>
<p>Cook: <strong><%= @recipe.cook_time %> min</strong></p>
</div>
<div class="recipe-details">
<section class="ingredients">
<h2>Ingredients</h2>
<ul id="ingredients-list">
<% @recipe.recipe_ingredients.each do |ri| %>
<li class="ingredients"><%= ri.quantity %> <%= ri.ingredient.name %> </li>
<% end %>
</ul>
</section>
<section class="directions">
<h2>Directions</h2>
<ul id="ingredients-list">
<% @recipe.directions.each do |dir| %>
<li class="ingredients"><%= dir.body %> </li>
<% end %>
</ul>
</section>
</div>

<h4>Comments</h4>

<% if user_signed_in? %>
<%= render partial: "comments/form", locals: { comment: Comment.new, commentable: @recipe } %>
<% else %>
<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "login", new_user_session_path %> to comment
<% end %>

<%= turbo_stream_from @recipe, :comments %>

<%= tag.div id: "#{dom_id(@recipe)}_comments" do %>
<%= render partial: "comments/comment_with_replies", collection: @recipe.comments.where(parent_id: nil), as: :comment %>
<% end %>


<% if user_signed_in? && current_user.id == @recipe.user_id %>
<%= link_to "Edit Recipe", edit_recipe_path, class: "btn btn-sm btn-info" %>
<%= link_to "Delete Recipe", recipe_path, method: :delete, class: "btn btn-sm btn-danger" %>
<% end %>
<%= link_to "Recipes Home", recipes_path, class: "btn btn-sm btn-secondary" %>
</div>
<div class="col-md-4">
<h2>Check out these other recipes</h2>
</div>
</div>
</section>