config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'
  # get "/profile/:username" => "users#profile", as: :profile

  devise_for :users, :path => 'account'

  get 'users/:username/profile', to: 'users#show', as: :user
  resources :users, param: :username do
    get 'users/:username/recipes', to: 'users#recipes', as: :recipes
    member do
      get :following, :followers
    end
  end
  
  resources :recipes do
    resources :comments, module: :recipes
  end
  
  resources :comments do
    resources :comments, module: :comments
  end

  resources :relationships, only: [:create, :destroy]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :profile_image
  has_many :recipes, dependent: :destroy
  has_many :comments
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships

  validates_presence_of :first_name, :last_name, :username, :admin
  validates_uniqueness_of :username, :email

  def fullname
    "#{first_name} #{last_name}"
  end

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def to_param
    username
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user


  def show
  
  end

  def recipes
    render 'user_recipes'
  end

  def following
    render 'following'
  end

  def followers
    render 'followers'
  end

  private

  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/users_helper.rb
module UsersHelper  
  def profile_image user
    image = user.profile_image.present? ? user.profile_image : "default.png"
    image_tag(image, class: "profile-pic m-r-10")
  end

  def follow_image user
    image = user.profile_image.present? ? user.profile_image : "default.png"
    image_tag(image, class: "follow-pic m-r-10")
  end

  def can_edit_profile? profile_id
    user_signed_in? && current_user.id == profile_id
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", id: "follow-btn", class: "btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
<% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
<% else %>
  <%= render 'follow' %>
<% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             local: true) do |f| %>
  <%= f.submit "Unfollow", id: "unfollow-btn", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%#= gravatar_for user, size: 50 %>
  <%= link_to user.username, user %>
  <%# <% if current_user.admin? && !current_user?(user) %>
    | <%#= link_to "delete", user, method: :delete,
    data: { confirm: "You sure?" } %>
  <%# end %>
</li>

app/views/users/followers.html.erb
<%= turbo_frame_tag @user do %>
  <div class="stats">
    <span> <%= link_to "Recipes", user_recipes_path(@user), collection: @user.recipes %></span>
    <span class="current"> <%= link_to "Followers", followers_user_path(@user), collection: @user.followers %></span>
    <span> <%= link_to "Following", following_user_path(@user), collection: @user.following %></span>
  </div>
  <% if @user.followers.empty? %>
    <div class="no-stats">
      <p>No followers yet.</p>
    </div>
  <% else %>
    <% @user.followers.each do |follower| %>
    <div class="row">
      <div class="col-4 col-md-4 profile-follow">
          <%= link_to user_path(follower.username), "data-turbo-frame": "_top" do  %>
          <div class="follow">
            <%= follow_image follower %>
          </div>
          <% end %>
        </div>        
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/following.html.erb
<%= turbo_frame_tag @user do %>
  <div class="stats">
    <span> <%= link_to "Recipes", user_recipes_path(@user), collection: @user.recipes %></span>
    <span> <%= link_to "Followers", followers_user_path(@user), collection: @user.followers %></span>
    <span class="current"> <%= link_to "Following", following_user_path(@user), collection: @user.following %></span>
  </div>
  <% if @user.following.empty? %>
    <div class="no-stats">
      <p>Not following anyone yet.</p>
    </div>
  <% else %>
    <% @user.following.each do |following| %>
    <div class="row">
      <div class="col-4 col-md-4 profile-follow">
          <%= link_to user_path(following.username), "data-turbo-frame": "_top" do  %>
          <div class="follow">
            <%= follow_image following %>
          </div>
          <% end %>
        </div>        
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <%#= profile_image @user, 200 %>
    </div>
    <div class="col-8 text-left">
      <div class="row">      
        <div class="col-8">
          <h1 class="float-left"><%= @user.username %></h1>
          <%= link_to "Edit Profile", edit_user_registration_path,class: "btn btn-muted btn-custom float-right" if can_edit_profile?(@user.id) %>
        </div>
      </div>
      <div class="row">
        <div class="col-4">
          <div class="profile-stats"><%= @user.recipes.count %> recipes</div>
        </div>
        <section class="stats">
          <%= render 'shared/relationship_stats' %>
        </section>
      </div>
      <%= render 'follow_form' if user_signed_in? && current_user.id != @user.id %>
      <p><%= @user.username %></p>
    </div>
  </div>
  <div class="row profile-recipes">
      <% @recipes.each do |recipe| %>
        <div class="col-4">
          <div class="recipe recipe-square" style="background: url(<%= rails_blob_url(recipe.image) %>) no-repeat center top">
            <%= link_to recipe_path(recipe) do  %>
              <div class="recipe-stats">
                <div class="inner">
                  <i class="fa fa-heart"></i> <%#= recipe.total_likes_count %>
                  <i class="fa fa-comment m-l-15"></i><%#= recipe.total_comments_count %> 
                </div>
              </div>
            <% end %>
          </div>        
        </div>
      <%end%>
  </div>
</div>

app/views/users/show.html.erb
<header>
  <div class="row profile-header">
    <div class="col-6 col-md-3 profile-image">
      <%= profile_image @user %>
    </div>
    <div class="col-6 col-md-9 text-left">
      <div class="row">      
        <h1 class="float-left"><%= @user.fullname %></h1>
      </div>
      <div class="row">
        <p>Joined <%= @user.created_at.strftime("%B %d, %Y") %></p>
      </div>
      <% if user_signed_in? && current_user.id != @user.id %>
        <div class="row">
          <%= render 'follow_form' %>
       </div>
      <% elsif can_edit_profile?(@user.id) %>        
        <div class="row">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</header>

<main>
  <%= turbo_frame_tag @user, src: user_recipes_path(@user) do%>
    <div class="stats">
      <span> <%= link_to "Recipes", user_recipes_path(@user), collection: @user.recipes %></span>
      <span> <%= link_to "Followers", followers_user_path(@user), collection: @user.followers %></span>
      <span> <%= link_to "Following", following_user_path(@user), collection: @user.following %></span>
    </div>
  <% end %>
</main>

app/views/users/user_recipes.html.erb
<%= turbo_frame_tag @user do %>
  <div class="stats">
    <span class="current"> <%= link_to "Recipes", user_recipes_path(@user), collection: @user.recipes %></span>
    <span> <%= link_to "Followers", followers_user_path(@user), collection: @user.followers %></span>
    <span> <%= link_to "Following", following_user_path(@user), collection: @user.following %></span>
  </div>
  <% if @user.recipes.empty? %>
    <div class="no-stats">
      <p>No recipes to display.</p>
    </div>
  <% else %>
    <div class="row profile-recipes">    
      <% @user.recipes.each do |recipe| %>
        <div class="col-6 col-md-4">
            <div class="card">
              <%= link_to recipe_path(recipe), "data-turbo-frame": "_top" do  %>
                  <%= recipe_thumbnail recipe %>
              <% end %>       
              <div class="card-body">
                <h5 class="card-title"><%= recipe.name.titleize %></h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>