config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'
  # get "/profile/:username" => "users#profile", as: :profile

  devise_for :users, :path => 'account'

  get 'users/:username/profile', to: 'users#show', as: :user
  resources :users, param: :username do
    get 'users/:username/recipes', to: 'users#recipes', as: :recipes
    member do
      get :following, :followers
    end
  end
  
  resources :recipes do
    resources :comments, module: :recipes
  end
  
  resources :comments do
    resources :comments, module: :comments
  end

  resources :relationships, only: [:create, :destroy]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<%if flash[:notice] %>
<div id="notification" class="alert alert-dismissible alert-success" data-controller="notification">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%=flash[:notice]%>
</div>
<%end%>

<%if flash[:alert] %>
    <div id="notification" class="alert alert-dismissible alert-warning" data-controller="notification">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
    </div>
<% end %>

<%if flash[:error]%>
    <div id="notification" class="alert alert-dismissible alert-danger" data-controller="notification">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%=flash[:error]%>
    </div>
<%end%>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" id="navbar">
  <%#= link_to root_path, class: "navbar-brand"  do %>
    <%#= image_tag("logo_dpi.png", class: "navbar-logo-image") %><span class="navbar-logo-text">My Recipe Box</span>
  <%# end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarScroll">
    <ul class="navbar-nav ml-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
      <li class="nav-item <%=is_active('/')%>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item dropdown <%=is_active('/profile/:username')%>">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Account
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "View My Profile", user_path(current_user.username), class: "nav-link" %>
          
          <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link", :method => :delete %>
        </div>
      </li>
      <li class="nav-item dropdown <%=nested_active('recipes')%>">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Recipes
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Recipes", recipes_path, class: "nav-link" %>

          <%= link_to "Create Recipe", new_recipe_path, class: "nav-link" %>
        </div>
      </li>
      <% end %>
      <% unless user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%=nested_active('recipes')%>">
        <%= link_to "Recipes", recipes_path, class: "nav-link" %>
      </li>            
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" id="navbar">
  <%#= link_to root_path, class: "navbar-brand"  do %>
    <%#= image_tag("logo_dpi.png", class: "navbar-logo-image") %><span class="navbar-logo-text">My Recipe Box</span>
  <%# end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarScroll">
    <ul class="navbar-nav ml-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
      <li class="nav-item <%=is_active('/')%>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item dropdown <%=is_active('/profile/:username')%>">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Account
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "View My Profile", user_path(current_user.username), class: "nav-link" %>
          
          <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link", :method => :delete %>
        </div>
      </li>
      <li class="nav-item dropdown <%=nested_active('recipes')%>">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Recipes
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Recipes", recipes_path, class: "nav-link" %>

          <%= link_to "Create Recipe", new_recipe_path, class: "nav-link" %>
        </div>
      </li>
      <% end %>
      <% unless user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%=nested_active('recipes')%>">
        <%= link_to "Recipes", recipes_path, class: "nav-link" %>
      </li>            
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRecipeBox</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if user_signed_in? %>
      <meta name="user-id" content="<%= current_user.id %>">
    <% else %>
      <meta name="user-id" content="guest">
    <% end %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="body">
    <%= render 'layouts/navigation'%>
    <div class="app container-fluid">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>